name: ofgconnects_mobile
description: "A Christian Social app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- 1. BACKEND & NETWORK ---
  appwrite: ^14.0.0
  minio: ^3.5.8
  flutter_dotenv: ^5.1.0

  # --- 2. STATE MANAGEMENT ---
  flutter_riverpod: ^2.6.1
  state_notifier: ^1.0.0

  # --- 3. NAVIGATION ---
  go_router: ^14.0.0

  # --- 4. MEDIA & UPLOAD ---
  image_picker: ^1.1.1
  image_cropper: ^8.0.2
  flutter_cache_manager: ^3.3.2
  path: ^1.9.0

  # --- 5. VIDEO PLAYER (MEDIA KIT) ---
  # Removed video_player & chewie
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4 # <--- CRITICAL for VP9 on iOS
  
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.2
  
  # --- 6. UTILITIES ---
  intl: ^0.19.0
  share_plus: ^12.0.1
  cupertino_icons: ^1.0.6

  # --- 7. MONETIZATION ---
  google_mobile_ads: ^5.1.0
  cached_network_image: ^3.4.1
  timeago: ^3.7.1
  video_player: ^2.10.1
  chewie: ^1.13.0

dependency_overrides:
  flutter_web_auth_2: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
    - assets/logoH.png